#!/bin/bash
set -e

# ─────────────────────────────────────────────────────────────────────────────
#  AegisSight v0.4.1 — Interactive Installer
# ─────────────────────────────────────────────────────────────────────────────

CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
BOLD='\033[1m'

echo ""
echo -e "${CYAN}${BOLD}"
echo "  ___   ___ ___ ___ ___ ___ ___ _  _ _____"
echo " / _ \ / __/ __|_ _/ __/ __|_ _| || |_   _|"
echo "| (_) |\\__ \\__ \\| |\\__ \\__ \\| || __ | | |  "
echo " \___/ |___/___/___|___/___/___|_||_| |_|  "
echo -e "        Self-Hosting Installer  ${GREEN}v0.4.1${CYAN}"
echo -e "${NC}"
echo ""

# ── Prerequisite checks ───────────────────────────────────────────────────────
echo -e "${YELLOW}Checking prerequisites...${NC}"

if ! command -v docker &>/dev/null; then
  echo -e "${RED}✗ Docker is not installed. Please install Docker first: https://docs.docker.com/get-docker/${NC}"
  exit 1
fi
echo -e "${GREEN}✓ Docker found${NC}"

if ! docker compose version &>/dev/null 2>&1; then
  echo -e "${RED}✗ Docker Compose v2 is not available. Run: docker plugin install compose${NC}"
  exit 1
fi
echo -e "${GREEN}✓ Docker Compose v2 found${NC}"

echo ""

# ── Gather configuration ──────────────────────────────────────────────────────
echo -e "${BOLD}── Step 1: Admin Account ────────────────────────────────────${NC}"
read -rp "  Admin username [admin]: " ADMIN_USERNAME
ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"

while true; do
  read -rsp "  Admin password (min 8 chars): " ADMIN_PASSWORD
  echo ""
  if [ ${#ADMIN_PASSWORD} -ge 8 ]; then
    break
  fi
  echo -e "${RED}  Password must be at least 8 characters.${NC}"
done

echo ""
echo -e "${BOLD}── Step 2: Domain & SSL ─────────────────────────────────────${NC}"
read -rp "  Your domain (e.g. aegis.example.com) [skip for IP-only]: " DOMAIN
DOMAIN="${DOMAIN:-localhost}"

LETSENCRYPT_EMAIL=""
if [ "$DOMAIN" != "localhost" ]; then
  read -rp "  Email for Let's Encrypt notifications: " LETSENCRYPT_EMAIL
fi

echo ""
echo -e "${BOLD}── Step 3: Port ─────────────────────────────────────────────${NC}"
read -rp "  Backend port [4000]: " PORT
PORT="${PORT:-4000}"

echo ""

# ── Write .env ────────────────────────────────────────────────────────────────
echo -e "${YELLOW}Writing .env...${NC}"

cat > .env <<EOF
# AegisSight v0.4.1 — Generated by install.sh
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
DOMAIN=${DOMAIN}
LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
PORT=${PORT}
ENCRYPTION_KEY=$(openssl rand -hex 32 2>/dev/null || tr -dc 'a-f0-9' </dev/urandom | head -c 64)
EOF

echo -e "${GREEN}✓ .env created${NC}"

# ── Build & launch ────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}Building and starting AegisSight...${NC}"
docker compose pull --quiet certbot nginx 2>/dev/null || true
docker compose up -d --build

echo ""
echo -e "${GREEN}${BOLD}✓ AegisSight v0.4.1 is running!${NC}"
echo ""

if [ "$DOMAIN" != "localhost" ]; then
  echo -e "  Dashboard:  ${CYAN}http://${DOMAIN}${NC}"
  echo -e "  To enable SSL, log into the dashboard → Settings → Enable SSL"
else
  echo -e "  Dashboard:  ${CYAN}http://localhost:80${NC}"
fi

echo ""
echo -e "  ${BOLD}Admin username:${NC} ${ADMIN_USERNAME}"
echo -e "  ${BOLD}Admin password:${NC} (the one you just set)"
echo ""
echo -e "  To view logs: ${YELLOW}docker compose logs -f${NC}"
echo ""
